export { default as Home } from './Home/Home'
export { default as ArtGallery } from './ArtGallery/ArtGallery'
export { default as About } from './About/About'
export { default as IndividualArtPage } from './IndividualArtPage/IndividualArtPage'
export { default as PageNotFoundpage } from './PageNotFoundpage/PageNotFoundpage'
